fix(encoder): 値が飛ぶバグを修正
sya-ri/HAL_Extension pull request #19
Opened 2023-11-16 11:12 UTC by alcedo-taku

値が counter period 分、飛ぶバグを修正しました。
（原因は1周期の間に複数回TIM_FLAGが立っていたときに、それを感知できなかったことだと思われます。）

2023-11-22 18:25 UTC, sya-ri requested changes
条件式をちょっと変えました。等価だと思いますが、試してもらえると嬉しいです

2023-11-22 18:25 UTC, sya-ri commented on tim/encoder.cpp
> +        if ((int32_t)(rawCount - lastRawCount) < (int32_t) - __HAL_TIM_GET_AUTORELOAD(htim) / 2) {
```suggestion
        if (((int32_t) (lastRawCount - rawCount)) > ((int32_t) (__HAL_TIM_GET_AUTORELOAD(htim) / 2))) { // overflow
```

2023-11-22 18:25 UTC, sya-ri commented on tim/encoder.cpp
> +        } else if ((int32_t)(rawCount - lastRawCount) > (int32_t) + __HAL_TIM_GET_AUTORELOAD(htim) / 2) {
```suggestion
        } else if (((int32_t) (rawCount - lastRawCount)) > ((int32_t) (__HAL_TIM_GET_AUTORELOAD(htim) / 2))) { // underflow
```

2023-12-07 15:25 UTC, sya-ri requested changes
確認遅れて申し訳ないです。インクルード消して問題なさそうなら消してほしいです。

2023-12-07 15:25 UTC, sya-ri commented on tim/encoder.cpp
> +#include <cmath>
```suggestion
```

cmath 使ってなさそう

2023-12-08 12:22 UTC, alcedo-taku commented
cmath を削除し、build が通ること、書き込んで実行できることを確かめました。
環境がすぐ用意できないため、エンコーダが使えるかどうかは確かめていません。
必要であれば確認しますが、いかがいたしますか？

2023-12-08 13:07 UTC, sya-ri approved these changes
大丈夫です、問題ないと思います

2023-12-08 13:07 UTC, merged