add(button): Buttonクラス，BooleanStateButtonクラスを追加
sya-ri/HAL_Extension pull request #31
Opened 2024-02-16 09:20 UTC by alcedo-taku

2024-03-15 02:39 UTC, sya-ri requested changes
遅くなっちゃいました。全体的にコードフォーマットも直してもらえると嬉しいです

2024-03-15 02:39 UTC, sya-ri commented on gpio/boolean_state_button.hpp
> +public:
コンストラクタは特になしですか？それとも using がそれの役割をしている？

2024-03-15 02:39 UTC, sya-ri commented on gpio/button.cpp
> +	return (lastState ^ state) & state;
boolの変数に対して論理演算をするのは良くないですね。型を変えるか処理を変えるかしたいです。

2024-03-15 02:39 UTC, sya-ri commented on gpio/button.cpp
> +	if(normalyState == GPIO_PIN_RESET) {
:: を使った enum の型指定をしたいです

2024-03-15 02:39 UTC, sya-ri commented on gpio/button.cpp
> +    gpio = GPIO(GPIOx, GPIO_Pin);
gpioも初期化の構文に入れるのはできませんかね。できないなら大丈夫です

2024-03-15 02:39 UTC, sya-ri commented on gpio/boolean_state_button.hpp
> +protected:
protectedはなくてもいいかもです

2024-03-29 11:59 UTC, alcedo-taku commented on gpio/boolean_state_button.hpp
> +public:
using によって，コンストラクタを継承しているつもりです．

2024-03-29 18:50 UTC, sya-ri requested changes

2024-03-29 18:50 UTC, sya-ri commented on gpio/button.cpp
> +    }
```suggestion
    return state && lastState != state;
```

2024-03-29 18:50 UTC, sya-ri commented on gpio/button.cpp
> +    }
```suggestion
    return !state && lastState != state;
```

2024-03-29 18:50 UTC, sya-ri commented on gpio/button.cpp
> +	if( HAL_GetTick() - rawChangeTime >= chatteringTime ) {
```suggestion
	if(chatteringTime <= (HAL_GetTick() - rawChangeTime)) {
```

2024-03-29 18:50 UTC, sya-ri commented on gpio/button.cpp
> +	}
```suggestion
	if (normalyState == GPIO_PinState::GPIO_PIN_RESET) {
	    rawState = gpio.isSet();
	} else {
	    rawState = gpio.isReset();
	}
```

2024-03-29 18:51 UTC, sya-ri commented
対応ありがとうございます。フォーマットやより簡略化できる表現についてレビューしました。おねがいします～

2024-04-05 03:31 UTC, alcedo-taku commented
修正しました～

2024-04-05 04:22 UTC, sya-ri approved these changes

2024-04-05 04:22 UTC, merged